Feature/#9 background image
Rednaxela700/CC-Project-2 pull request #38
Opened 2021-01-03 18:34 UTC by synowa

2021-01-03 21:40 UTC, paula0403 approved these changes

2021-01-03 23:39 UTC, DominikNowak requested changes

2021-01-03 23:39 UTC, DominikNowak commented on styles/_global.scss
> +  margin: 0%;
When you set something to 0, you don't have to specify a unit. There is already normalize.css in the project so that line is redundant anyway

2021-01-04 13:01 UTC, DominikNowak approved these changes

2021-01-04 13:03 UTC, merged