Feature/#3 menu options
Rednaxela700/CC-Project-2 pull request #40
Opened 2021-01-04 00:03 UTC by paula0403

2021-01-04 09:28 UTC, Enessetere approved these changes

2021-01-04 22:02 UTC, Rednaxela700 requested changes
- formatting issues?
- DRY, make a function instead of repeating yourself. Call it on `const options=[starships,vehicles,people];`
- check my [post](https://discord.com/channels/750077803881431154/780725708305072138/795397847368335370)  on discord
- I'd like your commits to be more descriptive. Consider "changes/changed" a banned word in your commit messages
- I wish other reviewers write this review. I don't want to be more annoying than I actually am. @Enessetere, @DominikNowak

2021-01-05 00:22 UTC, DominikNowak commented on styles/components/_buttonWhiteWithIcon.scss
> -    font-family: $font-primary;
I've kept your configuration, so honestly I have no idea. Empty lines at the end of file are adding with format, but in fact it is also making 2 spaces like here.

2021-01-05 01:07 UTC, Rednaxela700 commented on styles/components/_buttonWhiteWithIcon.scss
> -    font-family: $font-primary;
Then I guess @paula0403 has another formatter enabled. 
@paula0403 please let us know if you have VSC extensions like beautify, live sass compiler enabled or a local .editorconfig/similar file in your project.

2021-01-05 12:50 UTC, paula0403 commented on styles/components/_buttonWhiteWithIcon.scss
> -    font-family: $font-primary;
I have live sass compiler (VSC extension), but it doesn't work for me. Now uninstall this extension. Maybe it will help.

2021-01-06 02:44 UTC, DominikNowak requested changes
I've left a few comments. Also underline of options doesn't have box-shadow like on figma project.

2021-01-06 02:44 UTC, DominikNowak commented on styles/components/_MenuOptions.scss
> +.container {
camelCase in scss components files names [wiki](https://github.com/Rednaxela700/CC-Project-2/wiki#styling)

2021-01-06 02:44 UTC, DominikNowak commented on src/app/Components/MenuOptions.js
> +    let btn = document.createElement('button');
here should be const

2021-01-06 02:44 UTC, DominikNowak commented on src/app/Components/MenuOptions.js
> +      element.classList.remove('select_option');
Please look at [BEM class naming convention](http://getbem.com/naming/) and tweak these here

2021-01-06 17:17 UTC, Enessetere approved these changes
Looks good to me, code is formatted, works as designed, only thing to change is file name of SCSS file and in future implement trigger for picked mode

2021-01-06 17:17 UTC, Enessetere commented on styles/_components.scss
> +@import './components/menuOptions';
Your scss file starts with capital case letter, consider change to lower case letter, so it will pass GH checks.

2021-01-07 00:56 UTC, DominikNowak approved these changes
Well done :)

2021-01-13 21:09 UTC, closed without merging