attempt to fix PR#40
Rednaxela700/CC-Project-2 pull request #48
Opened 2021-01-07 03:05 UTC by DominikNowak

2021-01-07 14:47 UTC, Rednaxela700 requested changes
This code is a mess, I hope it will be cleaned up quickly 🧽 

Steps to take:
1. Reorganize
2. Cleanup
3. Double check 
4. Push

Also please keep commit messages explanatory. I'd like to know the process, see more than a single commit

2021-01-07 16:17 UTC, vieraboschkova commented on src/app/components/ModeMenu.js
> +      btnOption.style.color = 'rgba(0, 0, 0, 0.4)';
question concerning the app itself - can we define if we use rgb or hex for color definitions?

2021-01-07 16:23 UTC, vieraboschkova commented on styles/components/_modeMenu.scss
> +      font-family: $font-primary;
Thanks, that is something i never before organized in my code, although I tried...  So by type should be ok?
/* Positioning */
/* Display & Box Model */
/* Color */
/* Text */
 /* Other */

2021-01-07 21:53 UTC, paula0403 approved these changes

2021-01-07 22:48 UTC, vieraboschkova commented on styles/components/_modeMenu.scss
> +  &_button--select {
Maybe the structure could look like that: 
.menu {
  &__button {
    &--select{
      &::after{
      }
    }

2021-01-07 22:50 UTC, vieraboschkova reviewed
check the scss structure

2021-01-07 23:11 UTC, vieraboschkova approved these changes

2021-01-13 21:02 UTC, Rednaxela700 approved these changes

2021-01-13 21:09 UTC, merged